"""create initial table

Revision ID: 151e5cf7be3b
Revises: 
Create Date: 2023-12-16 14:52:17.312152

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151e5cf7be3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

now = datetime.now()

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ball_speeds_table = op.create_table('ball_speeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('speed'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_ball_speeds_id'), 'ball_speeds', ['id'], unique=False)

    # ball_speedsテーブルに初期データを登録（50～180を間隔5で登録）
    ball_speeds = list(range(50, 181, 5))
    for i, ball_speed in enumerate(ball_speeds):
        op.bulk_insert(ball_speeds_table, [
            {
                'id': i+1,
                "speed": ball_speed,
                "created": now,
                "updated": now
            }
        ])

    op.create_table('batting_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_batting_centers_id'), 'batting_centers', ['id'], unique=False)
    op.create_index(op.f('ix_batting_centers_place_id'), 'batting_centers', ['place_id'], unique=True)
    breaking_balls_table = op.create_table('breaking_balls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255, collation='utf8mb4_bin'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_breaking_balls_id'), 'breaking_balls', ['id'], unique=False)

    # breaking_ballsテーブルの初期データを登録
    op.bulk_insert(breaking_balls_table, [
        {
            'id': 1,
            "name": "ストレート",
            "created": now,
            "updated": now
        },
        {
            'id': 2,
            "name": "カーブ",
            "created": now,
            "updated": now
        },
        {
            'id': 3,
            "name": "シュート",
            "created": now,
            "updated": now
        },
        {
            'id': 4,
            "name": "スライダー",
            "created": now,
            "updated": now
        },
        {
            'id': 5,
            "name": "チェンジアップ",
            "created": now,
            "updated": now
        },
        {
            'id': 6,
            "name": "フォーク",
            "created": now,
            "updated": now
        },
    ])

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255, collation='utf8mb4_bin'), nullable=False),
    sa.Column('email', sa.String(length=255, collation='utf8mb4_bin'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('itta_users_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batting_center_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batting_center_id'], ['batting_centers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'batting_center_id', name='unique_idx_userid_battingcenterid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_itta_users_centers_id'), 'itta_users_centers', ['id'], unique=False)
    op.create_table('machine_informations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batting_center_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('batter_box', sa.String(length=255, collation='utf8mb4_bin'), nullable=False),
    sa.CheckConstraint("batter_box IN ('右', '左', '両')"),
    sa.ForeignKeyConstraint(['batting_center_id'], ['batting_centers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_machine_informations_id'), 'machine_informations', ['id'], unique=False)
    op.create_table('atta_users_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine_informations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'machine_id', name='unique_idx_atta_userid_machineid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_atta_users_machines_id'), 'atta_users_machines', ['id'], unique=False)
    op.create_table('machines_ball_speeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('ball_speed_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ball_speed_id'], ['ball_speeds.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machine_informations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'ball_speed_id', name='unique_idx_machine_id_ball_speed_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_machines_ball_speeds_id'), 'machines_ball_speeds', ['id'], unique=False)
    op.create_table('machines_breaking_balls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('breaking_ball_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['breaking_ball_id'], ['breaking_balls.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machine_informations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'breaking_ball_id', name='unique_idx_machine_id_breaking_ball_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_machines_breaking_balls_id'), 'machines_breaking_balls', ['id'], unique=False)
    op.create_table('nakatta_users_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine_informations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'machine_id', name='unique_idx_nakatta_userid_machineid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_nakatta_users_machines_id'), 'nakatta_users_machines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nakatta_users_machines_id'), table_name='nakatta_users_machines')
    op.drop_table('nakatta_users_machines')
    op.drop_index(op.f('ix_machines_breaking_balls_id'), table_name='machines_breaking_balls')
    op.drop_table('machines_breaking_balls')
    op.drop_index(op.f('ix_machines_ball_speeds_id'), table_name='machines_ball_speeds')
    op.drop_table('machines_ball_speeds')
    op.drop_index(op.f('ix_atta_users_machines_id'), table_name='atta_users_machines')
    op.drop_table('atta_users_machines')
    op.drop_index(op.f('ix_machine_informations_id'), table_name='machine_informations')
    op.drop_table('machine_informations')
    op.drop_index(op.f('ix_itta_users_centers_id'), table_name='itta_users_centers')
    op.drop_table('itta_users_centers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_breaking_balls_id'), table_name='breaking_balls')
    op.drop_table('breaking_balls')
    op.drop_index(op.f('ix_batting_centers_place_id'), table_name='batting_centers')
    op.drop_index(op.f('ix_batting_centers_id'), table_name='batting_centers')
    op.drop_table('batting_centers')
    op.drop_index(op.f('ix_ball_speeds_id'), table_name='ball_speeds')
    op.drop_table('ball_speeds')
    # ### end Alembic commands ###
