variable "app_name" {}
variable "stage" {}
variable "cognito_userool_id" {}
variable "cognito_client_id" {}
variable "find_place_api_key" {}
variable "db_user" {}
variable "db_password" {}
variable "db_host" {}
variable "db_port" {}
variable "resas_api_key" {}
