variable "app_name" {}
variable "stage" {}
variable "cognito_userool_id" {}
variable "cognito_client_id" {}
variable "find_place_url" {}
variable "place_details_url" {}
variable "find_place_api_key" {}
variable "photo_reference_url" {}
variable "db_user" {}
variable "db_password" {}
variable "db_host" {}
variable "db_port" {}